### ISSUE TITLE
you need xenforoa ddons

### ISSUE THREAD

**Issue by DavidJBrockway** [NetherManiacsKingdom/GladiatorMine#3]
i have the addons like pocketmine fromus

**Comment by matthew4444** [comment]
look i made,im alsmosdt done making the code go to our github then imagiaclmines http://nmk.navhost.com/test1.html

**Comment by DavidJBrockway** [comment]
erro

**Comment by matthew4444** [comment]
i got plugins,and alsmost done with tets1.html,ill be donewith it tommrow
