### ISSUE TITLE
Server Crash Issue

### ISSUE THREAD

**Issue by NetherOwner** [NetherManiacsKingdom/GladiatorMine#5]
Hey matthew when i turn the server it just stop and try again and again and it just stop when i trying to turn the server can you fix it

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
idk how to, but can someone help

**Comment by erkam2002** [comment]
I can thing i what is the problem?

**Comment by matthew4444** [comment]
hi

**Comment by matthew4444** [comment]
i dont understand youi

**Comment by matthew4444** [comment]
you

**Comment by matthew4444** [comment]
I DONT UNDERSTAND YOU @erkam2002

**Comment by erkam2002** [comment]
What is the Problem?

**Comment by erkam2002** [comment]
Crash report?

**Comment by matthew4444** [comment]
The servers crashes upon boot

**Comment by erkam2002** [comment]
Ok i test it

**Comment by matthew4444** [comment]
can u tell me what hapeens

**Comment by matthew4444** [comment]
HELLO?

**Comment by matthew4444** [comment]
Hey u on?

**Comment by matthew4444** [comment]
ANYONE ON?

**Comment by NetherOwner** [comment]
Matthew when i turn the server it just stop and so i downloaded pocketmine 0.14.0 and it work so the proplem is that gladiator mine dont work

**Comment by matthew4444** [comment]
HEY
CAN I HAVE CRASH DUMP

**Comment by NetherOwner** [comment]
There come no crash dump it just say opned server and stopped server nothing else

**Comment by matthew4444** [comment]
umm

**Comment by matthew4444** [comment]
can u make a screen recording of it

**Comment by matthew4444** [comment]
wiat

**Comment by matthew4444** [comment]
r u on windows

**Comment by NetherOwner** [comment]
?

**Comment by NetherOwner** [comment]
Nope

**Comment by matthew4444** [comment]
LINUX
?

**Comment by NetherOwner** [comment]
Android

**Comment by matthew4444** [comment]
OHH

**Comment by matthew4444** [comment]
GET MOBIZEN FROM PLAY STORE AND SCREEN RECORD WHEN U TURN ON UR SERVER

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
K

**Comment by NetherOwner** [comment]
How do i send it to you

**Comment by matthew4444** [comment]
MEDIAFIRE

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
AND DO U LIKE MY SITE HTTP://NMK.NAVHOST.COM

**Comment by PocketKiller** [comment]
YOU SHITZ, GIVE ME THE ERROR AND I'LL FIX

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
boot up the .phar in the realses tab

**Comment by matthew4444** [comment]
and u get a error

**Comment by matthew4444** [comment]
can u fix it

**Comment by PocketKiller** [comment]
I can't run my server now.

**Comment by matthew4444** [comment]
@PocketKiller  boot up the phar in the realses tab and u will get a error,can  u fix it?

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
well hey

**Comment by matthew4444** [comment]
liek my site http://nmk.navhost.com/

**Comment by matthew4444** [comment]
?

**Comment by PocketKiller** [comment]
Yes. nice

**Comment by matthew4444** [comment]
Pockeetkiller can u help finish build batle,thx

**Comment by matthew4444** [comment]
https://github.com/NetherManiacsKingdom/WorkingInProgress-Plugins-Sourcecode-For-Dev/tree/master/Build-Battle/Build-Battle-master

**Comment by matthew4444** [comment]
hello @PocketKiller

**Comment by DavidJBrockway** [comment]
Hey math

**Comment by DavidJBrockway** [comment]
What adding you use on gladiator mine

**Comment by matthew4444** [comment]
hey

**Comment by matthew4444** [comment]
like my site its done

**Comment by DavidJBrockway** [comment]
I have paid for gladatorMine.net and will Harv it to day for use let's use that domain

**Comment by matthew4444** [comment]
nmk.navhost.com

**Comment by matthew4444** [comment]
i uuploaded pluigins

**Comment by matthew4444** [comment]
on xenforo

**Comment by matthew4444** [comment]
mine is freree

**Comment by matthew4444** [comment]
lol ^^

**Comment by matthew4444** [comment]
http://www.dnsrsearch.com/index.php?origURL=http%3A//gladatormine.net/&r=&bc=****

**Comment by matthew4444** [comment]
POCKETKILLER TROLLS -.-

**Comment by DavidJBrockway** [comment]
Ik can use the domain site I paid for GladitorMine.net plz also am I still part of the team
I am code into tntrun

**Comment by matthew4444** [comment]
BUT GLADIATORMINE.NET DOESNT EXIST

**Comment by matthew4444** [comment]
I TYPED IT IN MY BROWSER

**Comment by DavidJBrockway** [comment]
Ok go addy dns update

**Comment by flaxues** [comment]
He probably didn't setted up the dns

**Comment by flaxues** [comment]
You see

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
@FLAXUES OK AND'

**Comment by matthew4444** [comment]
I MADE MY SITE

**Comment by DavidJBrockway** [comment]
The dns update to my web serevr that why

**Comment by matthew4444** [comment]
AND

**Comment by flaxues** [comment]
@matthew4444 Could you please stop spamming :) If someone doesn't react he/she is or busy or offline

**Comment by matthew4444** [comment]
HEY @FLAXUES SOMEONE IPBANED ME ON UR SERVER IDK WHY

**Comment by flaxues** [comment]
Can I get you website then?

**Comment by DavidJBrockway** [comment]
Well good I am coddling tntrun and I blow how to fix you erro skywars almost fixed and

**Comment by matthew4444** [comment]
NMK.NAVHOST.COM

**Comment by DavidJBrockway** [comment]
What I host serevr as we'll

**Comment by flaxues** [comment]
@DavidJBrockway What error do you get? now?

**Comment by matthew4444** [comment]
HEY @FLAXUES SOMEONE IPBANED ME ON UR SERVER IDK WHY

**Comment by matthew4444** [comment]
HEY @FLAXUES SOMEONE IPBANED ME ON UR SERVER IDK WH

**Comment by DavidJBrockway** [comment]
Read skywars it a small erro in arena loader

**Comment by flaxues** [comment]
@matthew4444 Can u gitter you're ip?

**Comment by matthew4444** [comment]
HEY @FLAXUES SOMEONE IPBANED ME ON UR SERVER IDK WHY (UR MINECRAFTR SERVER)

**Comment by matthew4444** [comment]
71.65.199.175

**Comment by DavidJBrockway** [comment]
It a small erro in a loader that disables the plugin no crash dump

**Comment by flaxues** [comment]
Never share you're ip publicly

**Comment by matthew4444** [comment]
CAN WE GET GLADIATORMINE WOERKING
OK

**Comment by DavidJBrockway** [comment]
I been making pocketmine in Java I ddos  you jk your up changes unspeakable static like mine for mine cart hosting

**Comment by DavidJBrockway** [comment]
Yes I made one in Java to day

**Comment by DavidJBrockway** [comment]
Dns is ready to be publish

**Comment by matthew4444** [comment]
CAN WE FIX GLADIATORMINE

**Comment by DavidJBrockway** [comment]
What is erro and can I fix it

**Comment by matthew4444** [comment]
WHAT HAPPENS WHEN U BOOT UP THE SERVER WITH GLADIATORMINE?

**Comment by DavidJBrockway** [comment]
I re code this

**Comment by matthew4444** [comment]
DID U FIX GLADIATORMINE

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
I KNOW

**Comment by matthew4444** [comment]
ITS PHP7 ,SO HE GOT ERROR BC POCKETMINE APP ONLY SUUPPORTS PHP5 -.- EHY DIDDNT I REMBER THAT ERIALER

**Comment by DavidJBrockway** [comment]
Almost

**Comment by matthew4444** [comment]
OK

**Comment by matthew4444** [comment]
U DONE?

**Comment by erkam2002** [comment]
I have testet i lt on PHP7 but it crash

**Comment by matthew4444** [comment]
U USING ANDROID EKHAM

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
ERKHAM R U USING ANDROID?

**Comment by flaxues** [comment]
@matthew4444 Accept my registration on you're forums!

**Comment by matthew4444** [comment]
K

**Comment by erkam2002** [comment]
No linux

**Comment by matthew4444** [comment]
K

**Comment by DavidJBrockway** [comment]
Yes nope not fixed try agin

**Comment by matthew4444** [comment]
K

**Comment by NetherOwner** [comment]
See it crash and i cant upload it fail

**Comment by NetherOwner** [comment]
What do we do

**Comment by matthew4444** [comment]
hey

**Comment by matthew4444** [comment]
Does it give u a "get lastest installer " msg

**Comment by DavidJBrockway** [comment]
i ahve fix

**Comment by matthew4444** [comment]
u d

**Comment by matthew4444** [comment]
u do?

**Comment by matthew4444** [comment]
what is it?

**Comment by matthew4444** [comment]
hello

**Comment by NetherOwner** [comment]
No it dont give me a message it only give me Server opned server stopped message nothing else

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
well someone said they have a fix

**Comment by matthew4444** [comment]
@DavidJBrockway said he had a fix 3 mins ago

**Comment by matthew4444** [comment]
hry

**Comment by matthew4444** [comment]
Hey @NetherOwner did u get ur email aproved on my fourms yet?

**Comment by NetherOwner** [comment]
Nope

**Comment by matthew4444** [comment]
well

**Comment by matthew4444** [comment]
i think i made u a valid user, np

**Comment by matthew4444** [comment]
u dont neede email confirmation,bc i made u a vaild user

**Comment by matthew4444** [comment]
a while ago

**Comment by matthew4444** [comment]
ill msg u @NetherOwner in fourms

**Comment by NetherOwner** [comment]
Kk

**Comment by NetherOwner** [comment]
Can you give me link to forum forgot it

**Comment by matthew4444** [comment]
k

**Comment by matthew4444** [comment]
http://nmk.navhost.com/xenforo/

**Comment by DavidJBrockway** [comment]
hey

**Comment by DavidJBrockway** [comment]
http://gladiatormine.net/

**Comment by NetherOwner** [comment]
Good but we need to fix the startup

**Comment by NetherOwner** [comment]
Because when i turn on the server it just stop it it only say opned server stopped server messages no crash dump only that what do we do

**Comment by matthew4444** [comment]
ok

**Comment by NetherOwner** [comment]
?

**Comment by matthew4444** [comment]
wtf man,he copyted my site

**Comment by NetherOwner** [comment]
Who

**Comment by matthew4444** [comment]
david aka the person who copys ouyr plugins -.

**Comment by matthew4444** [comment]
davdjbrockway

**Comment by NetherOwner** [comment]
And matthew how did you make that website because i want to make like that too but i cant code

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
i got a templte and coded it

**Comment by NetherOwner** [comment]
Ohh

**Comment by matthew4444** [comment]
and davidjbrockway copyed pour plugins also

**Comment by matthew4444** [comment]
most of them

**Comment by matthew4444** [comment]
he copyed my site -.-

**Comment by NetherOwner** [comment]
Ohh so if i give you a template you can make it to a code and past it to the website

**Comment by DavidJBrockway** [comment]
hey

**Comment by DavidJBrockway** [comment]
just made it on there for himeso the domain works cost £56.00 per year

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
hey u copyed my site

**Comment by DavidJBrockway** [comment]
my web server is a dedicetd srever 32 gb of ram

**Comment by DavidJBrockway** [comment]
do you wnat to use it add zenforo

**Comment by DavidJBrockway** [comment]
to show you it worked

**Comment by NetherOwner** [comment]
David can you fix this proplem listing Because when i turn on the server it just stop it its only say opned server stopped server messages no crash dump only that what do we do

**Comment by matthew4444** [comment]
U CAN IFRAME MY SITE BUT NOT DOWNLOAD ITS CODE AND UPLOAD IT TO UR SERVER VIA FTP

**Comment by matthew4444** [comment]
I ADDED XENFORO ON MY SITE

**Comment by DavidJBrockway** [comment]
you can move it

**Comment by DavidJBrockway** [comment]
to this webserver full root login email ect

**Comment by NetherOwner** [comment]
Matthew how did you make it to a code

**Comment by matthew4444** [comment]
i can ok thx

**Comment by DavidJBrockway** [comment]
may be config erro or server.php

**Comment by DavidJBrockway** [comment]
i give you root login now if you wnat

**Comment by matthew4444** [comment]
wht ftp login so i can copy it

**Comment by NetherOwner** [comment]
Ohhh

**Comment by DavidJBrockway** [comment]
math i have latest zenforo also you have fukll root login

**Comment by matthew4444** [comment]
ok

**Comment by NetherOwner** [comment]
David can you fix this proplem listing Because when i turn on the server it just stop it its only say opned server stopped server messages no crash dump only that what do we do

**Comment by DavidJBrockway** [comment]
yes
emai me at ZenaGamingsky@gmail.com
wont giev passsworld in chat

**Comment by matthew4444** [comment]
ok

**Comment by DavidJBrockway** [comment]
i can move a mysql serevr for you if you wnat

**Comment by NetherOwner** [comment]
David can you fix this proplem listing Because when i turn on the server it just stop it its only say opned server stopped server messages no crash dump only that what do we do

**Comment by NetherOwner** [comment]
David read the message

**Comment by matthew4444** [comment]
SENT IT

**Comment by matthew4444** [comment]
OK LET ME GET SQL

**Comment by NetherOwner** [comment]
Omg fuck this

**Comment by matthew4444** [comment]
SRLASY

**Comment by NetherOwner** [comment]
What

**Comment by DavidJBrockway** [comment]
hi i have fix

**Comment by NetherOwner** [comment]
To what!

**Comment by matthew4444** [comment]
hi

**Comment by matthew4444** [comment]
i sent u ftp login.bc i cant rembersql

**Comment by NetherOwner** [comment]
.......😡😑😐😒😪

**Comment by matthew4444** [comment]
umm

**Comment by DavidJBrockway** [comment]
the erro=i am moving site

**Comment by matthew4444** [comment]
r u giona move my ftp to ur site

**Comment by matthew4444** [comment]
andf ur loguin u gave me doesnt work

**Comment by DavidJBrockway** [comment]
yes i need your zenforo addons sent plz vvia email

**Comment by matthew4444** [comment]
CANT U MOVE MY SERVER VIA FTP TO UR SITE,IBC MY SERVER FOLDER HAS PLUGINS

**Comment by PocketKiller** [comment]
lol

**Comment by NetherOwner** [comment]
Wow did yo not have a fix for gladiator mine or we need to delete  the site :L

**Comment by matthew4444** [comment]
STOP @POCKETKILLER

**Comment by DavidJBrockway** [comment]
yes
]

**Comment by NetherOwner** [comment]
So what is it

**Comment by DavidJBrockway** [comment]
but still need addons as well

**Comment by DavidJBrockway** [comment]
what api.html and test.html

**Comment by NetherOwner** [comment]
?

**Comment by matthew4444** [comment]
OHH THAT WAS OLD IN OLD TESTING FILES BUT THEY DONT WORK

**Comment by DavidJBrockway** [comment]
pocketkiller
can you unban me on imgixalmine

**Comment by matthew4444** [comment]
DONT DELTE ANYTHING OFF MY SITE PLZ

**Comment by DavidJBrockway** [comment]
the sub folder for the formus.gladiatormine is that ok

**Comment by DavidJBrockway** [comment]
can you sent addons via email plz just in case

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
cant send addons via email due to im on a micro computer running a small laggy port of devbain

**Comment by matthew4444** [comment]
debian

**Comment by NetherOwner** [comment]
DAVID fix gladiatormine if you want BUT YOU NEED TO MAKE EnderAuth- Email.php!!!!

**Comment by DavidJBrockway** [comment]
dont close this

**Comment by DavidJBrockway** [comment]
files uplaoding

**Comment by matthew4444** [comment]
ya dont close it

**Comment by NetherOwner** [comment]
Why not

**Comment by DavidJBrockway** [comment]
send addons plz

**Comment by matthew4444** [comment]
ok its uploading thx. how long,bc were making fourms befpore y we awnser ur question

**Comment by NetherOwner** [comment]
You guys talk about something else this is issue help so we need someone to fix it

**Comment by matthew4444** [comment]
XENFORO FOLDER IN FTP HAS ADDON FILES IN IT,UR UPLOADING ZXXENFORO FOLDER RIGHT,THEN THE ADDONS R UPLAODING

**Comment by NetherOwner** [comment]
Sooo

**Comment by matthew4444** [comment]
WERE TALKING ABOUT WHAT WER DOING WITH THE SITE BEFORE WE AWNSER UR QUESTION -.-

**Comment by DavidJBrockway** [comment]
ok

**Comment by matthew4444** [comment]
DAVID DID U UPLOAD IT

**Comment by DavidJBrockway** [comment]
yes but we also need addon zip

**Comment by NetherOwner** [comment]
Okay i now you answar my quastion about 100 years rigth

**Comment by DavidJBrockway** [comment]
hi i take 15 mins

**Comment by DavidJBrockway** [comment]
hi it take 1 mins laods of files

**Comment by matthew4444** [comment]
ADDONS R IN THE XEOFORO FOLDLER U UPLOADED

**Comment by DavidJBrockway** [comment]
k

**Comment by DavidJBrockway** [comment]
wgat are the files for index.html

**Comment by DavidJBrockway** [comment]
ok i found fix for the srever

**Comment by matthew4444** [comment]
WHICH INDEX.HTML

**Comment by DavidJBrockway** [comment]
the main one not in zenforo

**Comment by matthew4444** [comment]
ohh,thats forn  the homepage

**Comment by DavidJBrockway** [comment]
ok

**Comment by matthew4444** [comment]
ohh,thats for the homepage

**Comment by matthew4444** [comment]
and can u add these files (i messed up on transfering them) https://github.com/xfrocks/Arcade

**Comment by DavidJBrockway** [comment]
do we need api

**Comment by matthew4444** [comment]
no api.html ortest.html dfont delte them dfrom my ftp

**Comment by DavidJBrockway** [comment]
k

**Comment by matthew4444** [comment]
dont delte themn from my ftp

**Comment by DavidJBrockway** [comment]
kk

**Comment by matthew4444** [comment]
we need u to upload xenforo folder to http://fourms.gladiatormine.net

**Comment by DavidJBrockway** [comment]
ik i am

**Comment by DavidJBrockway** [comment]
downalkidn gthen upaloding

**Comment by matthew4444** [comment]
how long,thx

**Comment by DavidJBrockway** [comment]
20 mins may be

**Comment by DavidJBrockway** [comment]
uplaoding to my server now

**Comment by matthew4444** [comment]
the login u gave me for ftp is invaild,and i need to chnage the links in index.html when u finish with the fourms

**Comment by matthew4444** [comment]
ok

**Comment by DavidJBrockway** [comment]
it for web server not fftop

**Comment by DavidJBrockway** [comment]
my ffftp is
ip 160.153.162.10
name davidbrockway

you nkow password

**Comment by DavidJBrockway** [comment]
dont tampure wioth pocketserver.co.uk my hosting company

**Comment by matthew4444** [comment]
ohh can u send me them again,bc it doesnt work when i use the link yugave me with the login u gave me,im not messing with that im making the index.html work with ythe fourms ur uploading

**Comment by DavidJBrockway** [comment]
sent

**Comment by DavidJBrockway** [comment]
your srever files are home page in zenforo

**Comment by DavidJBrockway** [comment]
whatadmin login for zenforo

**Comment by matthew4444** [comment]
THX

**Comment by DavidJBrockway** [comment]
site is moved almost

**Comment by DavidJBrockway** [comment]
email regestio working can i have admin login

**Comment by DavidJBrockway** [comment]
home page on gladtormine wont work can you fix it

**Comment by matthew4444** [comment]
ITS NAVHOST.COM USER:nmk password:nmk

**Comment by matthew4444** [comment]
I AM

**Comment by DavidJBrockway** [comment]
for zenforo

**Comment by DavidJBrockway** [comment]
it going to old link can we reinstall zenforo new vearsion

**Comment by DavidJBrockway** [comment]
i have 1.5.6 ready to install

**Comment by matthew4444** [comment]
WIAT

**Comment by matthew4444** [comment]
DID U UPLOAD MY FOURM

**Comment by DavidJBrockway** [comment]
it wont work need mysql

**Comment by DavidJBrockway** [comment]
yes

**Comment by matthew4444** [comment]
ILL TRY AGAIN TO GET IT

**Comment by DavidJBrockway** [comment]
i intsll zenforo and add ypour addons it work fine alos i have yours backedup

**Comment by matthew4444** [comment]
IM INSTALLING XENFORO

**Comment by matthew4444** [comment]
UPLOADING XENFORO TO FOURMS

**Comment by DavidJBrockway** [comment]
where

**Comment by DavidJBrockway** [comment]
on my web server

**Comment by DavidJBrockway** [comment]
i have add 1.5.6

**Comment by DavidJBrockway** [comment]
well

**Comment by matthew4444** [comment]
I WAS GOING TO MIOVE XENFORO FOLDEER FROM MY SERVER TO FOURMS.GLADIATORMINE.NET TO UR SERVER,

**Comment by matthew4444** [comment]
HUI

**Comment by DavidJBrockway** [comment]
i add 1.5.6

**Comment by DavidJBrockway** [comment]
http://forums.gladiatormine.net/install/index.php?install/

**Comment by DavidJBrockway** [comment]
i setup mysql andadmin for ypu and send login

**Comment by matthew4444** [comment]
OK

**Comment by matthew4444** [comment]
move "/nmk/xenforo/' on
ftp://server02nav.host
user:NMK
PASS:daredare
to fourms.gladiatormine.net

**Comment by DavidJBrockway** [comment]
nope new install i installa addons

**Comment by matthew4444** [comment]
u didnt even insta;ll xenforo look

**Comment by DavidJBrockway** [comment]
setting mysql up

**Comment by DavidJBrockway** [comment]
i did

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
did u put mysql yet

**Comment by DavidJBrockway** [comment]
support@gladiatormine.net  is main email

**Comment by DavidJBrockway** [comment]
yes

**Comment by matthew4444** [comment]
ook

**Comment by DavidJBrockway** [comment]
prrocessing

**Comment by matthew4444** [comment]
that trakes a while

**Comment by DavidJBrockway** [comment]
it installed i add oddons now

**Comment by matthew4444** [comment]
ok
heres the theme

**Comment by matthew4444** [comment]
http://nmk.navhost.com/xenforo/admin.php?styles/default-style.1/export

**Comment by DavidJBrockway** [comment]
ok

**Comment by matthew4444** [comment]
login mattplayzmcpe@gmail.com daredare

**Comment by matthew4444** [comment]
can u give me admin in xenforo on fourms.gladiatormine.net

**Comment by DavidJBrockway** [comment]
yes vua email when themm done

**Comment by matthew4444** [comment]
?

**Comment by DavidJBrockway** [comment]
sent login in email

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
what the user

**Comment by DavidJBrockway** [comment]
look at the them

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
WHATS MY USER

**Comment by DavidJBrockway** [comment]
register i sent you admin vua email

**Comment by matthew4444** [comment]
i got it

**Comment by matthew4444** [comment]
hey

**Comment by DavidJBrockway** [comment]
look at them now

**Comment by DavidJBrockway** [comment]
it has nether portal

**Comment by matthew4444** [comment]
i did,and we need resource manager  for the plugins

**Comment by DavidJBrockway** [comment]
ik and add the addons

**Comment by matthew4444** [comment]
http://nmk.navhost.com/xenforo/index.php?resources/categories/gladiatormine-plugins.2/

**Comment by DavidJBrockway** [comment]
i am installing stuff alos make plugins to the author

**Comment by matthew4444** [comment]
i am

**Comment by DavidJBrockway** [comment]
i have installed zenforo resource mager

**Comment by matthew4444** [comment]
ok i will add plugins now

**Comment by DavidJBrockway** [comment]
kk

**Comment by DavidJBrockway** [comment]
can i add some cool like addons

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
can u install this https://github.com/xfrocks/Arcade

**Comment by DavidJBrockway** [comment]
i just got fetured prioducets i paid it it cost $5

**Comment by DavidJBrockway** [comment]
http://www.xen-factory.com/index.php?resources/rm-featured-resources-rm-sidebar-block.62/
yes

**Comment by matthew4444** [comment]
ok

**Comment by DavidJBrockway** [comment]
look what on plugin page now

**Comment by matthew4444** [comment]
can u install this https://github.com/xfrocks/Arcade

**Comment by DavidJBrockway** [comment]
yes

**Comment by matthew4444** [comment]
im starting to upload the plugins

**Comment by DavidJBrockway** [comment]
ok

**Comment by DavidJBrockway** [comment]
i upfarde the reosurcemanger to new version re add plugins

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
did u add xfgames

**Comment by DavidJBrockway** [comment]
you idk how

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
wtf man u delt3ed resource mgr

**Comment by DavidJBrockway** [comment]
it beging fixed

**Comment by matthew4444** [comment]
?

**Comment by DavidJBrockway** [comment]
fixed

**Comment by matthew4444** [comment]
k

**Comment by DavidJBrockway** [comment]
there a erro

**Comment by DavidJBrockway** [comment]
Mysqli prepare error: Unknown column 'allow_submit_user_group_ids' in 'field list'

Zend_Db_Statement_Mysqli->_prepare() in Zend/Db/Statement.php at line 115
Zend_Db_Statement->__construct() in Zend/Db/Adapter/Mysqli.php at line 381
Zend_Db_Adapter_Mysqli->prepare() in Zend/Db/Adapter/Abstract.php at line 478
Zend_Db_Adapter_Abstract->query() in XenResource/Install/Controller.php at line 37
XenResource_Install_Controller::install()
call_user_func() in XenForo/Model/AddOn.php at line 215
XenForo_Model_AddOn->installAddOnXml() in XenForo/Model/AddOn.php at line 169
XenForo_Model_AddOn->installAddOnXmlFromFile() in XenForo/ControllerAdmin/AddOn.php at line 188
XenForo_ControllerAdmin_AddOn->actionInstall() in XenForo/FrontController.php at line 351
XenForo_FrontController->dispatch() in XenForo/FrontController.php at line 134
XenForo_FrontController->run() in /home/davidbrockway/public_html/gladiatormine.net/forums/admin.php at li

**Comment by DavidJBrockway** [comment]
i re up load

**Comment by DavidJBrockway** [comment]
do you ahve the addon zip

**Comment by matthew4444** [comment]
i gtg dinner brb 5-15 mins

**Comment by DavidJBrockway** [comment]
send the reousce file plz in zip

**Comment by matthew4444** [comment]
hey
u on

**Comment by matthew4444** [comment]
@davidjbrockway TELL ME MY NAVHOST..COM PASSWORD, SOMEONE CHNAGED IT,TELL ME IT NOW

**Comment by DavidJBrockway** [comment]
I can't change it

**Comment by DavidJBrockway** [comment]
I can't change it via fftp

**Comment by DavidJBrockway** [comment]
http://forums.gladiatormine.net/index.php?resources/ new think is there also i upadte the them style so it works

**Comment by DavidJBrockway** [comment]
what happend to forumus

**Comment by flaxues** [comment]
@DavidJBrockway It got hacked and @matthew4444 reinstalled it!

**Comment by DavidJBrockway** [comment]
ik i need to chage passwolrd removeing fromus reisbnatllling now

**Comment by DavidJBrockway** [comment]
why you got hacked

**Comment by DavidJBrockway** [comment]
in wont  give admin out any more then

**Comment by DavidJBrockway** [comment]
he added a stupid addon

**Comment by DavidJBrockway** [comment]
i lost all my websitev

**Comment by DavidJBrockway** [comment]
fuckibng you

**Comment by matthew4444** [comment]
FOURM BACK UP AND RUNNING
