### ISSUE TITLE
SOMEONE HACKED THE FOURMS(FIXED)

### ISSUE THREAD

**Issue by matthew4444** [NetherManiacsKingdom/GladiatorMine#6]
I WAS ADDING XENFORO RESOURCE MANAGER FOR PLUGINS,TRHEN THIS POPED UP
UR SITE GOT HACKED,
WWTF HAPPEND ,HELPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

**Comment by matthew4444** [comment]
SOMONE CHANGED MY NAVHOST PASSWORD A.LSO

**Comment by matthew4444** [comment]
HELPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

**Comment by Edwardthedog2** [comment]
Try resetting your password!!

**Comment by matthew4444** [comment]
I CANT

**Comment by matthew4444** [comment]
SOMEONE HACKED THE FOURMS

**Comment by matthew4444** [comment]
MY FOURMS AND @DAVIDS FOURM

**Comment by matthew4444** [comment]
@DavidJBrockway

**Comment by matthew4444** [comment]
FOURMS.GLADIATORMINE.NET

**Comment by matthew4444** [comment]
OMNMFG,IT WENT OFFLINE WTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

**Comment by Edwardthedog2** [comment]
I can't help you, I'm afraid. Why don't you contact NavHost's support?

**Comment by matthew4444** [comment]
UI WILL,AND SOMEONE IS JACKING GLADIATORMINE.NET NOW

**Comment by matthew4444** [comment]
OMFG

**Comment by matthew4444** [comment]
WTF SOMEONE JACKED UP THE SITE

**Comment by matthew4444** [comment]
LOOK http://forums.gladiatormine.net/index.php

**Comment by Edwardthedog2** [comment]
I saw. I just researched ".exe family" and found nothing.

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
im fixing the error

**Comment by matthew4444** [comment]
almost domne fixing it

**Comment by Edwardthedog2** [comment]
Have you fixed it yet?

**Comment by matthew4444** [comment]
yass

**Comment by matthew4444** [comment]
the website is resettting it selfr due to i couldmnt get ba backup of index.php

**Comment by matthew4444** [comment]
Hey edward

**Comment by Edwardthedog2** [comment]
Yeah?

**Comment by matthew4444** [comment]
umm i need to reinstall the whjole siyte

**Comment by Edwardthedog2** [comment]
oh no!!

**Comment by matthew4444** [comment]
BC THE SITE'S FILE HAD TO BE MADE AGAIN OR IT WONT BE A FOURM SADLY, I WISH THERE WAQS ANTHOER WAY,IM REINTSALIINNG THE FOURM

**Comment by Edwardthedog2** [comment]
Okay.

**Comment by matthew4444** [comment]
AND WE NEED TO WORK ON BUILD ABTTLE

**Comment by Skull3x** [comment]
There's a reason on why they hacked you
They said...
Reason To Hacked : Stop copying things and claim it that you made it!

What happened there??

**Comment by matthew4444** [comment]
IDK

**Comment by Skull3x** [comment]
Hm

**Comment by Skull3x** [comment]
Alert your hoster, the website you created yours on

**Comment by Skull3x** [comment]
Like for ex. Xenforo, Weebly, the rest

**Comment by matthew4444** [comment]
IM FIXING THE SITE,BC THE HOST GAVE ME ACCESS

**Comment by Skull3x** [comment]
Good, honestly there has been allot of hacking lately..

**Comment by matthew4444** [comment]
ya

**Comment by Skull3x** [comment]
I hope you can fix it, anyway we all can contribute to getting our site under control again? "Your site to be exact"

**Comment by matthew4444** [comment]
its almost done installing fourm again

**Comment by Skull3x** [comment]
:dancers:

**Comment by Skull3x** [comment]
:+1:  :DDDD

**Comment by Skull3x** [comment]
I don't see how that can just happen, you should really look into your host's security because that's ridiculous

**Comment by matthew4444** [comment]
i know

**Comment by matthew4444** [comment]
ikr

**Comment by Edwardthedog2** [comment]
Yeah. I own a really secure hosting company. [HostiFree](http://hostifree.info)

**Comment by matthew4444** [comment]
Installition Complete ^^

**Comment by Skull3x** [comment]
How tf did they hack that?? How is the law not involved. You can't just hack and get away with it. That's dangerous to local businesses and stuff

**Comment by Skull3x** [comment]
Congratulations xD

**Comment by Edwardthedog2** [comment]
Okay, good!!! Seriously though, you need to check out how secure the host is.

**Comment by matthew4444** [comment]
TELL @DAVIDBROCKWAY IF U SEE HIM,THAT THE FOURM'S ADMIN PASSWORD AND USER AND PASSWORD ARE SAME AS BEFORE

**Comment by matthew4444** [comment]
@DAVIDJBROCKWAY

**Comment by Edwardthedog2** [comment]
Okay, will do.

**Comment by matthew4444** [comment]
IM CLOSING THE ISSUE NOW

**Comment by Skull3x** [comment]
Kkkk

**Comment by flaxues** [comment]
Anyone online?

**Comment by flaxues** [comment]
You should add "xenporta 2 PRO" to the forum and can I get permissions to upload plugins?

**Comment by matthew4444** [comment]
i will give u premission to upload plugins
