### ISSUE TITLE
Server Crash Issue

### ISSUE THREAD

**Issue by matthew4444** [NetherManiacsKingdom/GladiatorMine#7]
-NetherOwner said: Hey matthew when i turn the server it just stop and try again and again and it just stop when i trying to turn the server can you fix it
-DavidJBrockWay Said A While later: there may be config error on server.php
- PLZ REPLY

**Comment by HittmanA** [comment]
Wow you guys have done a lot since i've been away! What did I miss?

**Comment by matthew4444** [comment]
gladiatormine crash,umm website coding , gladiatormine.net, fourms.gladiatormine.net, i didnt know u had hittmana.com,the useal,and u on hitmanna?

**Comment by matthew4444** [comment]
and endgenertaor plugin doesnt work

**Comment by matthew4444** [comment]
u on?

**Comment by HittmanA** [comment]
Hey I'm back

**Comment by HittmanA** [comment]
You didn't know i had hittmana.com? Lol I would think its obvious!

**Comment by HittmanA** [comment]
DUDE CAN I HELP WITH FORUMS.GLADIATORMINE.NET!?!?!?!

**Comment by HittmanA** [comment]
MATT?!

**Comment by matthew4444** [comment]
NO,WE FINSIHED IT LOL ^^,BUT U CAN BE A ADMIN,JUST REGISTER

**Comment by matthew4444** [comment]
HITTMANNA?!

**Comment by HittmanA** [comment]
YES

**Comment by matthew4444** [comment]
CAN U REGISTER

**Comment by HittmanA** [comment]
As admin I can edit stuff right?

**Comment by matthew4444** [comment]
ILL MAKE U SUPER ADMIN

**Comment by HittmanA** [comment]
I already registered!

**Comment by matthew4444** [comment]
YASYAS

**Comment by matthew4444** [comment]
OK

**Comment by matthew4444** [comment]
REGISTER AGAIN

**Comment by erkam2002** [comment]
Matthew

**Comment by HittmanA** [comment]
Btw why did you add trade pro without asking me?!

**Comment by erkam2002** [comment]
I have registed on forum

**Comment by matthew4444** [comment]
SRRY I THOUGHT THIS WAS PUBLICPLUGIN DEV GROUP ?

**Comment by erkam2002** [comment]
Can you give me a Rank?

**Comment by erkam2002** [comment]
Moderator? Or admin?

**Comment by HittmanA** [comment]
I just wanted you to ask me matthew.

**Comment by matthew4444** [comment]
YAS ULL BOTH GET SUPER ADMIN GIVE ME A MIN

**Comment by HittmanA** [comment]
Ok i reregistered

**Comment by matthew4444** [comment]
BTW WHY DID U DO THAT FAMILY.EXE THING,I DELETED

**Comment by HittmanA** [comment]
Who me?

**Comment by matthew4444** [comment]
YAS

**Comment by HittmanA** [comment]
I didn't.

**Comment by HittmanA** [comment]
Idk what that is.

**Comment by matthew4444** [comment]
WHO DID.I DELTED IT AND CAHNGED MY PASSWORD

**Comment by HittmanA** [comment]
Besides I use mac not windows so I can't use .exe

**Comment by HittmanA** [comment]
I use mac not windows so I can't use .exe

**Comment by matthew4444** [comment]
SOMEONE HACKED MY SITE A WHILE AGO,AND SAID THAT STOP COPYING MY PLUGINS,IDK WHT THT'S ABOUT?

**Comment by HittmanA** [comment]
Idk either and stop the uppercase plz

**Comment by matthew4444** [comment]
ok im making u both super admin in a min

**Comment by HittmanA** [comment]
Thx!

**Comment by HittmanA** [comment]
I can edit the stuff right? I saw some stuff that needs fixing.

**Comment by matthew4444** [comment]
ya,i fixed login  bug also

**Comment by HittmanA** [comment]
Ok am i admin now?

**Comment by erkam2002** [comment]
And i?

**Comment by matthew4444** [comment]
my micropc lags,almsost

**Comment by HittmanA** [comment]
ok

**Comment by matthew4444** [comment]
my micropc lags

**Comment by erkam2002** [comment]
?!?

**Comment by HittmanA** [comment]
Did it do it yet?

**Comment by HittmanA** [comment]
Matthew?

**Comment by HittmanA** [comment]
Matthew!?!?!

**Comment by matthew4444** [comment]
one user is super admin

**Comment by HittmanA** [comment]
Who? me?

**Comment by matthew4444** [comment]
ur about to be

**Comment by HittmanA** [comment]
Thanks!

**Comment by matthew4444** [comment]
did u get it

**Comment by HittmanA** [comment]
Checking...

**Comment by HittmanA** [comment]
Nope

**Comment by HittmanA** [comment]
You admitted HittmanA right?

**Comment by matthew4444** [comment]
1 sec

**Comment by HittmanA** [comment]
k

**Comment by matthew4444** [comment]
321 poof u got super admin powers

**Comment by HittmanA** [comment]
it doesn't list me as staff

**Comment by matthew4444** [comment]
ill ad you

**Comment by HittmanA** [comment]
k thanks!

**Comment by HittmanA** [comment]
I don't have permissions to do anything :/

**Comment by matthew4444** [comment]
im setting it

**Comment by HittmanA** [comment]
Ok thanks again!

**Comment by HittmanA** [comment]
YES now it shows me!

**Comment by matthew4444** [comment]
u got super admin

**Comment by HittmanA** [comment]
THANKS! :) :)

**Comment by matthew4444** [comment]
np

**Comment by matthew4444** [comment]
np

**Comment by HittmanA** [comment]
it won't let me unlock conversations and stuff. I need to edit one.

**Comment by HittmanA** [comment]
nvm

**Comment by matthew4444** [comment]
im fixing it

**Comment by HittmanA** [comment]
Nvm i can got to the cp now!

**Comment by HittmanA** [comment]
Matthew?

**Comment by matthew4444** [comment]
yas

**Comment by HittmanA** [comment]
Did you change the style of the forums?

**Comment by matthew4444** [comment]
yas

**Comment by HittmanA** [comment]
why?!

**Comment by matthew4444** [comment]
no i didnt

**Comment by HittmanA** [comment]
It appears all blue and white now?!

**Comment by HittmanA** [comment]
nvm

**Comment by HittmanA** [comment]
it fixed itself

**Comment by matthew4444** [comment]
i changed it to minecraft now

**Comment by HittmanA** [comment]
good

**Comment by HittmanA** [comment]
how can I add a new tab besides the plugins and other tabs?

**Comment by matthew4444** [comment]
umm what name

**Comment by matthew4444** [comment]
wht tab called

**Comment by HittmanA** [comment]
Just tell me how. I need to know. Tell me where I can find how to edit it.

**Comment by matthew4444** [comment]
i dont recomend u do it but https://xenforo.com/community/threads/how-to-add-a-new-tab-in-the-navbar.7781/

**Comment by HittmanA** [comment]
Its a good thing I know how to code in HTML and CSS so all that code I understand :)

**Comment by matthew4444** [comment]
^^

**Comment by HittmanA** [comment]
Lol I can easily edit this! May I be the web designer for the forums?

**Comment by matthew4444** [comment]
yas

**Comment by HittmanA** [comment]
thx!

**Comment by matthew4444** [comment]
np ^^

**Comment by matthew4444** [comment]
wht up

**Comment by HittmanA** [comment]
Just editing the code and uploading it :) trying to make our forums the best EVER!!

**Comment by HittmanA** [comment]
DUDE LOOK IT WORKED!!!

**Comment by matthew4444** [comment]
thx

**Comment by HittmanA** [comment]
Np!

**Comment by HittmanA** [comment]
Look I added a get gladiator mine tab!

**Comment by HittmanA** [comment]
Tell me if you change the style ok! It is important!

**Comment by matthew4444** [comment]
gladiatormine.net

**Comment by matthew4444** [comment]
ok

**Comment by HittmanA** [comment]
yes

**Comment by HittmanA** [comment]
Test the new tab

**Comment by matthew4444** [comment]
k

**Comment by HittmanA** [comment]
Why aren't you using the minecraft style?

**Comment by matthew4444** [comment]
i am but someone chaning it

**Comment by HittmanA** [comment]
Ok

**Comment by HittmanA** [comment]
Does gladiator mine actually work and whats the difference between it and pm?

**Comment by matthew4444** [comment]
I TOLD THE ADMIN TO STOP

**Comment by HittmanA** [comment]
good!

**Comment by HittmanA** [comment]
who is the admin?

**Comment by HittmanA** [comment]
I fixed it.

**Comment by matthew4444** [comment]
gladiatormine needs fixing and its just a fork of imagiaclmine@davidjbrockway

**Comment by HittmanA** [comment]
Then whats special about it?

**Comment by matthew4444** [comment]
i dunno

**Comment by HittmanA** [comment]
TELL ADMIN TO STOP HE CHANGED IT AGAIJ!

**Comment by matthew4444** [comment]
i am

**Comment by matthew4444** [comment]
hes making a new theme he said

**Comment by HittmanA** [comment]
Tell him to keep it on minecraft till he's done

**Comment by HittmanA** [comment]
who is he?

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
@davidjbrockway is he and http://forums.gladiatormine.net/index.php?conversations/stop-chhanging-theme-i-like-minecraft-theme-and-hitmanna-is-making-the-theme-better.3/

**Comment by HittmanA** [comment]
ok and lol

**Comment by matthew4444** [comment]
np

**Comment by HittmanA** [comment]
how do I add a new page?

**Comment by matthew4444** [comment]
is it a fourm

**Comment by HittmanA** [comment]
no

**Comment by matthew4444** [comment]
is it a thered a page a fourm a link fourm

**Comment by HittmanA** [comment]
thered?

**Comment by matthew4444** [comment]
http://forums.gladiatormine.net/admin.php?nodes/

**Comment by HittmanA** [comment]
That is a node and I can't figure out how to edit node pages

**Comment by matthew4444** [comment]
-.- look at the sidebar

**Comment by matthew4444** [comment]
brb dinner

**Comment by HittmanA** [comment]
Ok bye

**Comment by matthew4444** [comment]
5-15 mins

**Comment by HittmanA** [comment]
ok i added a new smiley

**Comment by matthew4444** [comment]
cool

**Comment by HittmanA** [comment]
type in creeper

**Comment by HittmanA** [comment]
in the forums

**Comment by HittmanA** [comment]
then type Hittmana

**Comment by HittmanA** [comment]
then type waffle

**Comment by matthew4444** [comment]
ok

**Comment by HittmanA** [comment]
then type chicken

**Comment by matthew4444** [comment]
lol

**Comment by HittmanA** [comment]
Like it?

**Comment by HittmanA** [comment]
try chicken

**Comment by matthew4444** [comment]
yas,ok

**Comment by HittmanA** [comment]
Lol

**Comment by matthew4444** [comment]
im gona post a joke in fourm in a min

**Comment by HittmanA** [comment]
Ok also important question: No one can download the plugins. It says you don't have permission. Even I can't download them.

**Comment by matthew4444** [comment]
im fixing it

**Comment by HittmanA** [comment]
ok where do I find that stuff ( for future reference)

**Comment by matthew4444** [comment]
gladiatormine.net and click plugins

**Comment by HittmanA** [comment]
oh ok

**Comment by HittmanA** [comment]
I fixed it

**Comment by HittmanA** [comment]
You change the user perm to allow download

**Comment by matthew4444** [comment]
make user perm . so that guest can donload plugins

**Comment by HittmanA** [comment]
i did

**Comment by matthew4444** [comment]
k

**Comment by HittmanA** [comment]
ok everyone can download plugins now

**Comment by HittmanA** [comment]
Ummm plugins can be submitted without approval. We need to fix that ASAP

**Comment by DavidJBrockway** [comment]
ik

**Comment by matthew4444** [comment]
i fixed it

**Comment by NetherOwner** [comment]
What did you fix plss say that you fixed this issue

**Comment by matthew4444** [comment]
im gettingf xf arcade on the fourms http://www.generalchatter.co.uk/arcade

**Comment by NetherOwner** [comment]
But matthew what did you fix?

**Comment by NetherOwner** [comment]
Matthew i am endbeast and what did you fix

**Comment by flaxues** [comment]
He fixed the permissions on the forums
@NetherOwner

**Comment by NetherOwner** [comment]
Okay but i want this issue fixed

**Comment by erkam2002** [comment]
Can you test Gladiatormine work it?

**Comment by NetherOwner** [comment]
Kk give me link to phar of gladiatormine

**Comment by matthew4444** [comment]
hello

**Comment by matthew4444** [comment]
https://github.com/NetherManiacsKingdom/GladiatorMine/issues/8

**Comment by NetherOwner** [comment]
Dont close this issue we didnt fix the issue
